name: dart3_node_interop
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  # currently not using this package since the preamble is hard coded
  node_preamble: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^3.0.0
  test: ^1.24.0
