name: vscode_interop
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  dart3_node_interop:
    path: ../../
  js: 0.6.3

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^3.0.0
  # test: ^1.24.0
